version: '3'
services:
  app: 
    build: .
    ports:
      - "8080:8080"
    healthcheck:
      test: curl --fail -s http://localhost:3000/ || exit 1
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s